typeidea/typeidea/urls.py
'''
@Author: Tye
@Date: 2020-03-23 14:51:44
@LastEditTime: 2020-04-03 15:14:45
@Description: 
'''

from django.conf.urls import url
from django.contrib import admin

from blog.views import (
    IndexView, CategoryView, TagView, SearchView, AuthorView, PostDetailView
)
from config.views import LinkListView
from .custom_site import custom_site

from comment.views import CommentView



urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    url(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author-list'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^super_admin/', admin.site.urls, name='super-admin'),
    url(r'^admin/', custom_site.urls, name='admin'),  # 配置自定义站点
]

typeidea/comment/models.py
'''
@Author: Tye
@Date: 2020-03-23 22:56:11
@LastEditTime: 2020-04-03 14:11:49
@LastEditors: Please set LastEditors
@Description: Comment Model
'''
from django.db import models

from blog.models import Post    # 导入Post类，用于设置外键关联

# Create your models here.
# """ 评论模型 """
class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, "正常"),
        (STATUS_DELETE, "删除"),
    )

    # target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="评论目标")    
    target = models.CharField(max_length=100, verbose_name="评论目标")  # 修改target字段类型，让其更通用   
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    # 获取最近评论
    @classmethod
    def latest_comments(cls):
        return cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-created_time')
    

    # 返回指定文章或友链下的所有有效评论
    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL).order_by('-created_time')


    class Meta:
        verbose_name = verbose_name_plural = "评论"
        ordering = ['-id']  # 根据id进行降序排列

typeidea/comment/forms.py
'''
@Author: Tye
@Date: 2020-04-03 13:41:21
@LastEditTime: 2020-04-14 17:29:43
@Description: comments used Model.Form
'''
from django import forms

from.models import Comment

import mistune      # 引入markdown三方库


# 评论需要用到的Form表单模型
class CommentForm(forms.ModelForm):
    # 表单字段-昵称设置
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(                  # 控件展示样式
            attrs={'class': 'form-control', 'style': 'width: 60%;'}
        )
    )

    # 表单字段-邮箱设置
    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': 'width: 60%;'}
        )
    )

    # 表单字段-网站设置
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': 'width: 60%;'}
        )
    )

    # 表单字段-内容设置
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'class': 'form-control', 'rows': 6, 'cols': 60}
        )
    )


    # 处理对应宇段数据的方法
    def clean_content(self):
        content = self.cleaned_data.get('content')  # 获取需要处理的字段
        # 判断评论内容，如果内容太少，直接抛出异常
        if len(content) < 10:
            raise forms.ValidationError('内容长度怎么能这么短呢！!')
        content = mistune.markdown(content)
        return content


    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

typeidea/comment/views.py
'''
@Author: Tye
@Date: 2020-03-23 23:56:58
@LastEditTime: 2020-04-03 14:52:48
@Description: 
'''
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import CommentForm

# Create your views here.
class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False
        
        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }

        return self.render_to_response(context)

typeidea/typeidea/themes/bootstrap/templates/comment/block.html
<!--
 * @Author: Tye
 * @Date: 2020-04-14 16:23:42
 * @LastEditTime: 2020-04-14 17:39:18
 * @Description: 
 -->
 <hr/>
 <!-- 评论部分展示 -->
 <div class="comment">
     <form class="form-group" action="/comment/" method="POST">
         {% csrf_token %}
         <input name="target" type="hidden" value="{{ target }}">
         {{ comment_form }}
         <input type="submit" value='写好了！'>
     </form>

     <ul class="list-group">
         {% for comment in comment_list %}
         <li class="list-group-item">
             <div class="nickname">
                 <a href="{{ comment.website }}">{{ comment.nickname}}</a>
                 <span>{{ comment.created_time }}</span>
             </div>
             <div class="comment-content">
                 {% autoescape off %}       <!-- 关闭Django自带的自动转码功能 -->
                 {{ comment.content }}
                 {% endautoescape %}
             </div>
         </li>
         {% endfor %}
     </ul>
 </div>

typeidea/typeidea/themes/bootstrap/templates/comment/result.html
<!--
 * @Author: Tye
 * @Date: 2020-04-03 15:00:12
 * @LastEditTime: 2020-04-03 15:11:11
 * @Description: 
 -->
 <!DOCTYPE html>
 <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>评论结果页</title>
        <style>
            body {text-align: center;}

            .result {
                text-align: center;
                width: 40%;
                margin: auto;
            }
            .errorlist {color: red;}

            ul li {
                list-style-type: None;
            }
        </style>
    </head>

    <body>
        <div class="result">
            {% if succeed %}
                评论成功！
                <a href="{{ target }}">返回</a>
            {% else %}
                <ul class="errorlist">
                    {% for field, message in form.errors.items %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                <a href="javascript:window.history.back();">返回</a>
            {% endif %}
        </div>
    </body>
 </html>